// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywdeodksmaujgormygok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3ZGVvZGtzbWF1amdvcm15Z29rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDIyNzAsImV4cCI6MjA2MzkxODI3MH0.rIEi71NePNGloaUAka8ou2MZ3NHV2NiXXFIvSyQVPYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);